{% set version = "1.24.0_280" %}
{% set bootstrapping = os.environ.get('CONDA_BUILD_BOOTSTRAPPING', '') %}

package:
  name: crosstool-ng
  version: {{ version }}

source:
  git_url: https://github.com/conda-forge/crosstool-ng.git
  git_tag: bootstrapping
  patches:
    - verbosity.patch

build:
{% if bootstrapping == 'yes' %}
  number: 3
{% else %}
  number: 4
{% endif %}
  skip: True  # [not unix]
  missing_dso_whitelist:
    - '*'
{% if bootstrapping == 'yes' %}
  string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_bootstrapping
{% else %}
  string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
{% endif %}

{% if bootstrapping != 'yes' %}
requirements:
  build:
    # TODO We need some [not bootstrapping] selector or something?
    - {{ compiler('c') }}
    - autoconf
    - automake
    - texinfo
    - bison
    - flex
    - git
    - help2man
    - make
    - texinfo
    - unzip
    - wget
    - sed  # [osx]
    - gawk  # [osx]
  host:
    - ncurses
    - libtool
    - flex
    - bison
    - bash  # [osx]
    - gettext  # [osx]
  run:
    - ncurses
    - libtool
    - bash  # [osx]
    - sed  # [osx]
    - gawk  # [osx]
{% endif %}

test:
  commands:
    - ct-ng
    - test -f $PREFIX/share/crosstool-ng/packages/glibc/2.17/1272-glibc-rh1211100.patch
    - test -f $PREFIX/share/crosstool-ng/config/versions/linux.in

about:
  home: http://crosstool-ng.org/
  license: GPL-2.0-or-later
  license_file:
    - COPYING
    - licenses.d/gpl.txt
    - licenses.d/lgpl.txt
    - licenses.d/by-sa/deed.en
    - licenses.d/by-sa/legalcode
  summary: A versatile (cross-)toolchain generator.
  dev_url: https://github.com/crosstool-ng/crosstool-ng

extra:
  recipe-maintainers:
    - isuruf
    - beckermr
    - katietz
    - mingwandroid
